# Series and DataFrames
Series is like a one dimensional numpy array with axis lables
DataFrame on the other hand is like a multi dimensional numpy array with labels on rows and columns

In [1]:
#importing numpy and pandas
import pandas as pd
import numpy as np

# Creating Series
Series can be created from python list, dictionary and numpy arrays

In [2]:
#creating the series from a python list
python_list = [4,5,6,7,8]
pd.Series(python_list)

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [3]:
#creating a series from a python list with custom index
python_list_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
pd.Series(python_list_week, index = python_list_week)

Monday          Monday
Tuesday        Tuesday
Wednesday    Wednesday
Thursday      Thursday
Friday          Friday
dtype: object

In [4]:
#creating the series from a dictionary
countries_code = { 1:"United States of America",
                  91: "India",
                  45: "Tunisia",
                  83: "Malta"

}
pd.Series(countries_code)

1     United States of America
91                       India
45                     Tunisia
83                       Malta
dtype: object

In [5]:
d = {1:'a', 2:'b', 3:'c', 4:'d'}
pd.Series(d)

1    a
2    b
3    c
4    d
dtype: object

In [6]:
#creating the series from numpy array
array = np.array([2,3,4,5,6])
pd.Series(array)

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [7]:
pd.Series(array, index=['a', 'b', 'c', 'd', 'e'])

a    2
b    3
c    4
d    5
e    6
dtype: int64

# Creating DataFrames
DataFrames are the most used Pandas data structure. It can be created from a dictionary, 2D array, and Series.

In [8]:
#creating a dataFrame from a dictionary
countries = {'Name' : ['USA', 'India', 'German', 'Rwanda'],
             'Code': [1, 91, 49, 250]

}
pd.DataFrame(countries)

     Name  Code
0     USA     1
1   India    91
2  German    49
3  Rwanda   250

In [9]:
#creating a dataFrame from a 2D array
#You pass the list of columns
df_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
pd.DataFrame(df_array, columns = ['a', 'b', 'c'])

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
#creating a dataFrame from a pandas series
#pass the columns in a list
countries_code = { "United States": 1,
                 "India": 91,
                 "Germany": 49,
                 "China": 86,
                 "Rwanda":250}
pd_series = pd.Series(countries_code)
pd.Series(countries_code)
df = pd.DataFrame(pd_series, columns = ['Code'])
df

               Code
United States     1
India            91
Germany          49
China            86
Rwanda          250

In [11]:
#adding a column
df['Population'] = [100, 450, 575, 2343,2323]
df

               Code  Population
United States     1         100
India            91         450
Germany          49         575
China            86        2343
Rwanda          250        2323

In [12]:
#removing a column
df.drop('Population', axis=1)

               Code
United States     1
India            91
Germany          49
China            86
Rwanda          250

In [13]:
df.columns

Index(['Code', 'Population'], dtype='object')

In [14]:
df.keys

<bound method NDFrame.keys of                Code  Population
United States     1         100
India            91         450
Germany          49         575
China            86        2343
Rwanda          250        2323>

In [15]:
df.index

Index(['United States', 'India', 'Germany', 'China', 'Rwanda'], dtype='object')

## B. Data Indexing, Selection and Iteration

In [17]:
#creating Dataframe from a dictionary
countries = {
    'Name': ['USA', 'India', 'Germany', 'Rwanda'],
    'Code': [1, 91, 49, 250]
}
df = pd.DataFrame(countries, index=['a', 'b', 'c', 'd'])
df

      Name  Code
a      USA     1
b    India    91
c  Germany    49
d   Rwanda   250

In [18]:
df['Name']

a        USA
b      India
c    Germany
d     Rwanda
Name: Name, dtype: object

In [19]:
df['Code']

a      1
b     91
c     49
d    250
Name: Code, dtype: int64

In [20]:
df.Name

a        USA
b      India
c    Germany
d     Rwanda
Name: Name, dtype: object

In [22]:
## When you have many columns, columns in list will be selected

df [['Name', 'Code']]

      Name  Code
a      USA     1
b    India    91
c  Germany    49
d   Rwanda   250

In [23]:
#this will return the first two rows
df[0:2]

    Name  Code
a    USA     1
b  India    91

In [25]:
#checking missing values
df3 = pd.DataFrame( np.array([[1,2,3], [4,np.nan,6], [7,np.nan,np.nan]]),
                   columns = ['column 1', 'column 2', 'column 3'])
df3

   column 1  column 2  column 3
0       1.0       2.0       3.0
1       4.0       NaN       6.0
2       7.0       NaN       NaN

In [28]:
df3.isnull()
#recognising missing values

   column 1  column 2  column 3
0     False     False     False
1     False      True     False
2     False      True      True

In [29]:
#calculating number of the missing values in each feature
df3.isnull().sum()

column 1    0
column 2    2
column 3    1
dtype: int64

In [31]:
#recognising non missing values
df3.notna()

   column 1  column 2  column 3
0      True      True      True
1      True     False      True
2      True     False     False

In [32]:
df3.notna().sum()

column 1    3
column 2    1
column 3    2
dtype: int64

In [33]:
#removing missing values
df3.dropna()

   column 1  column 2  column 3
0       1.0       2.0       3.0

In [34]:
df3.fillna(10)

   column 1  column 2  column 3
0       1.0       2.0       3.0
1       4.0      10.0       6.0
2       7.0      10.0      10.0

In [35]:
df3.fillna('fillme')

   column 1 column 2 column 3
0       1.0      2.0      3.0
1       4.0   fillme      6.0
2       7.0   fillme   fillme

# D. More Operations and functions
this section introduces the more useful functions of Pandas

In [36]:
df4 = pd.DataFrame({'Product Name':['Shirt','Boot','Bag'],
              'Order Number':[45,56,64],
              'Total Quantity':[10,5,9]},
              columns = ['Product Name', 'Order Number', 'Total Quantity'])

In [37]:
#retrieving basic info about the dataframe
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product Name    3 non-null      object
 1   Order Number    3 non-null      int64
 2   Total Quantity  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [38]:
#return dataframe columns
df4.columns

Index(['Product Name', 'Order Number', 'Total Quantity'], dtype='object')

In [43]:
#return dataframe data
df4.keys

<bound method NDFrame.keys of   Product Name  Order Number  Total Quantity
0        Shirt            45              10
1         Boot            56               5
2          Bag            64               9>

In [47]:
#return the head of the dataframe
df4.head(1)

  Product Name  Order Number  Total Quantity
0        Shirt            45              10

In [49]:
#return the tail of dataframe
df4.tail(1)

  Product Name  Order Number  Total Quantity
2          Bag            64               9

In [50]:
#return numpy arrays of the dataframe
df4.values

array([['Shirt', 45, 10],
       ['Boot', 56, 5],
       ['Bag', 64, 9]], dtype=object)

In [51]:
#return the size or number of elements in a dataframe
df4.size

9

In [52]:
df4.shape

(3, 3)

In [53]:
df4['Product Name'].unique()

array(['Shirt', 'Boot', 'Bag'], dtype=object)

In [54]:
#applting a function to a dataframe
def double_quantity(x):
  return x * x

In [55]:
df4['Total Quantity'].apply(double_quantity)

0    100
1     25
2     81
Name: Total Quantity, dtype: int64

In [57]:
# You can also apply an anonymous function to a dataframe
# Squaring each value in dataframe

df5 = pd.DataFrame([[1,2], [4,5]], columns=['col1', 'col2'])

df5.map(lambda x: x**2)

   col1  col2
0     1     4
1    16    25

In [58]:
#sorting values in dataframe
df4.sort_values(['Order Number'])

  Product Name  Order Number  Total Quantity
0        Shirt            45              10
1         Boot            56               5
2          Bag            64               9

In [59]:
df4.sort_values(['Order Number'], ascending=False)

  Product Name  Order Number  Total Quantity
2          Bag            64               9
1         Boot            56               5
0        Shirt            45              10

# Aggregation Methods

In [60]:
df4

  Product Name  Order Number  Total Quantity
0        Shirt            45              10
1         Boot            56               5
2          Bag            64               9

In [62]:
df4.describe()

       Order Number  Total Quantity
count      3.000000        3.000000
mean      55.000000        8.000000
std        9.539392        2.645751
min       45.000000        5.000000
25%       50.500000        7.000000
50%       56.000000        9.000000
75%       60.000000        9.500000
max       64.000000       10.000000

In [63]:
df4.describe().transpose()

                count  mean       std   min   25%   50%   75%   max
Order Number      3.0  55.0  9.539392  45.0  50.5  56.0  60.0  64.0
Total Quantity    3.0   8.0  2.645751   5.0   7.0   9.0   9.5  10.0

In [64]:
df4['Total Quantity'].std()

2.6457513110645907

## F. Groupby
`Group by` involves splitting data into groups, applying function to each group, and combining the results.

In [65]:
df4 = pd.DataFrame({'Product Name':['Shirt','Boot','Bag', 'Ankle', 'Pullover', 'Boot', 'Ankle', 'Tshirt', 'Shirt'],
              'Order Number':[45,56,64, 34, 67, 56, 34, 89, 45],
              'Total Quantity':[10,5,9, 11, 11, 8, 14, 23, 10]},
              columns = ['Product Name', 'Order Number', 'Total Quantity'])

In [66]:
df4

  Product Name  Order Number  Total Quantity
0        Shirt            45              10
1         Boot            56               5
2          Bag            64               9
3        Ankle            34              11
4     Pullover            67              11
5         Boot            56               8
6        Ankle            34              14
7       Tshirt            89              23
8        Shirt            45              10

In [67]:
#we want to group the df by the product name
df4.groupby('Product Name').mean()

              Order Number  Total Quantity
Product Name
Ankle                 34.0            12.5
Bag                   64.0             9.0
Boot                  56.0             6.5
Pullover              67.0            11.0
Shirt                 45.0            10.0
Tshirt                89.0            23.0

In [68]:
df4.groupby('Product Name').sum()

              Order Number  Total Quantity
Product Name
Ankle                   68              25
Bag                     64               9
Boot                   112              13
Pullover                67              11
Shirt                   90              20
Tshirt                  89              23

In [69]:
#you can also use aggregation after groupby
df4.groupby('Product Name').aggregate(['mean', 'min', 'max', 'sum', 'std', 'var'])

             Order Number                        Total Quantity              \
                     mean min max  sum  std  var           mean min max sum
Product Name
Ankle                34.0  34  34   68  0.0  0.0           12.5  11  14  25
Bag                  64.0  64  64   64  NaN  NaN            9.0   9   9   9
Boot                 56.0  56  56  112  0.0  0.0            6.5   5   8  13
Pullover             67.0  67  67   67  NaN  NaN           11.0  11  11  11
Shirt                45.0  45  45   90  0.0  0.0           10.0  10  10  20
Tshirt               89.0  89  89   89  NaN  NaN           23.0  23  23  23


                  std  var
Product Name
Ankle         2.12132  4.5
Bag               NaN  NaN
Boot          2.12132  4.5
Pullover          NaN  NaN
Shirt         0.00000  0.0
Tshirt            NaN  NaN

# H. Beyond Dataframes: Working with CSV and Excel

In [71]:
data = pd.read_csv('/housing.csv')

In [73]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [74]:
type(data)

pandas.core.frame.DataFrame

In [75]:
data.to_csv('/housing_dataset', index=False)

In [77]:
dataset = pd.read_csv('/housing_dataset')
dataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [78]:
type(dataset)

pandas.core.frame.DataFrame

In [79]:
##exporting csv to excel
data.to_excel('/housing_dataset.xlsx', index=False)

In [80]:
excel_data = pd.read_excel('/housing_dataset.xlsx')
excel_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,INLAND

In [81]:
excel_data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY

# Real World: Exploratory Data Analysis (EDA)

In [84]:
wine_data = pd.read_csv('/winequality-red.csv')

In [85]:
wine_data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [86]:
wine_data.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [87]:
wine_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
fixed acidity,1599.0,8.319637,1.741096,4.60000,7.1000,7.90000,9.200000,15.90000
volatile acidity,1599.0,0.527821,0.179060,0.12000,0.3900,0.52000,0.640000,1.58000
citric acid,1599.0,0.270976,0.194801,0.00000,0.0900,0.26000,0.420000,1.00000
residual sugar,1599.0,2.538806,1.409928,0.90000,1.9000,2.20000,2.600000,15.50000
chlorides,1599.0,0.087467,0.047065,0.01200,0.0700,0.07900,0.090000,0.61100
free sulfur dioxide,1599.0,15.874922,10.460157,1.00000,7.0000,14.00000,21.000000,72.00000
total sulfur dioxide,1599.0,46.467792,32.895324,6.00000,22.0000,38.00000,62.000000,289.00000
density,1599.0,0.996747,0.001887,0.99007,0.9956,0.99675,0.997835,1.00369
pH,1599.0,3.311113,0.154386,2.74000,3.2100,3.31000,3.400000,4.01000
sulphates,1599.0,0.658149,0.169507,0.33000,0.5500,0.62000,0.730000,2.00000
alcohol,1599.0,10.422983,1.065668,8.40000,9.5000,10.20000,11.100000,14.90000
quality,1599.0,5.636023,0.807569,3.00000,5.0000,6.00000,6.000000,8.00000

In [88]:
wine_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [89]:
#checking for missing values
wine_data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [90]:
# wine quality range from 0 to 10. The higher the quality value, the good wine is

wine_data['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [91]:
wine_data.groupby(['fixed acidity', 'volatile acidity', 'citric acid']).sum()

                                            residual sugar  chlorides  \
fixed acidity volatile acidity citric acid
4.6           0.520            0.15                    2.1      0.054
4.7           0.600            0.17                    2.3      0.058
4.9           0.420            0.00                    2.1      0.048
5.0           0.380            0.01                    1.6      0.048
              0.400            0.50                    4.3      0.046
...                                                    ...        ...
15.0          0.210            0.44                    4.4      0.150
15.5          0.645            0.49                    8.4      0.190
15.6          0.645            0.49                    4.2      0.095
              0.685            0.76                    3.7      0.100
15.9          0.360            0.65                    7.5      0.096

                                            free sulfur dioxide  \
fixed acidity volatile acidity citric acid
4.6           0.520            0.15                         8.0
4.7           0.600            0.17                        17.0
4.9           0.420            0.00                        16.0
5.0           0.380            0.01                        26.0
              0.400            0.50                        29.0
...                                                         ...
15.0          0.210            0.44                        20.0
15.5          0.645            0.49                        20.0
15.6          0.645            0.49                        10.0
              0.685            0.76                         6.0
15.9          0.360            0.65                        22.0

                                            total sulfur dioxide  density  \
fixed acidity volatile acidity citric acid
4.6           0.520            0.15                         65.0  0.99340
4.7           0.600            0.17                        106.0  0.99320
4.9           0.420            0.00                         42.0  0.99154
5.0           0.380            0.01                         60.0  0.99084
              0.400            0.50                         80.0  0.99020
...                                                          ...      ...
15.0          0.210            0.44                         48.0  2.00010
15.5          0.645            0.49                         46.0  2.00630
15.6          0.645            0.49                         23.0  1.00315
              0.685            0.76                         43.0  1.00320
15.9          0.360            0.65                         71.0  0.99760

                                              pH  sulphates  alcohol  quality
fixed acidity volatile acidity citric acid
4.6           0.520            0.15         3.90       0.56     13.1        4
4.7           0.600            0.17         3.85       0.60     12.9        6
4.9           0.420            0.00         3.71       0.74     14.0        7
5.0           0.380            0.01         3.70       0.75     14.0        6
              0.400            0.50         3.49       0.66     13.6        6
...                                          ...        ...      ...      ...
15.0          0.210            0.44         6.14       1.68     18.4       14
15.5          0.645            0.49         5.84       1.48     22.2       10
15.6          0.645            0.49         2.92       0.74     11.1        5
              0.685            0.76         2.95       0.68     11.2        7
15.9          0.360            0.65         2.98       0.84     14.9        5

[1333 rows x 9 columns]

In [92]:
wine_data.groupby(['free sulfur dioxide', 'total sulfur dioxide']).sum()

                                          fixed acidity  volatile acidity  \
free sulfur dioxide total sulfur dioxide
1.0                 28.0                           18.2             0.440
                    44.0                            7.9             0.400
2.0                 45.0                            7.9             0.400
3.0                 6.0                            33.0             1.215
                    7.0                            25.8             1.520
...                                                 ...               ...
55.0                95.0                           20.4             1.080
57.0                135.0                           5.9             0.190
66.0                115.0                           6.9             0.630
68.0                124.0                          13.2             1.470
72.0                160.0                           5.9             0.290

                                          citric acid  residual sugar  \
free sulfur dioxide total sulfur dioxide
1.0                 28.0                         0.48             4.2
                    44.0                         0.29             1.8
2.0                 45.0                         0.30             1.8
3.0                 6.0                          1.38             5.0
                    7.0                          0.63             6.0
...                                               ...             ...
55.0                95.0                         0.74            30.8
57.0                135.0                        0.21             1.7
66.0                115.0                        0.33             6.7
68.0                124.0                        0.04            15.8
72.0                160.0                        0.25            13.4

                                          chlorides  density    pH  sulphates  \
free sulfur dioxide total sulfur dioxide
1.0                 28.0                      0.156  1.99800  6.82       1.74
                    44.0                      0.157  0.99730  3.30       0.92
2.0                 45.0                      0.157  0.99727  3.31       0.91
3.0                 6.0                       0.229  2.98892  9.53       1.93
                    7.0                       0.242  2.98210  9.63       1.50
...                                             ...      ...   ...        ...
55.0                95.0                      0.428  2.00738  6.36       1.54
57.0                135.0                     0.045  0.99341  3.32       0.44
66.0                115.0                     0.235  0.99787  3.22       0.56
68.0                124.0                     0.244  1.99880  6.94       1.06
72.0                160.0                     0.067  0.99721  3.33       0.54

                                          alcohol  quality
free sulfur dioxide total sulfur dioxide
1.0                 28.0                     20.6       12
                    44.0                      9.5        6
2.0                 45.0                      9.5        6
3.0                 6.0                      32.7       16
                    7.0                      35.6       18
...                                           ...      ...
55.0                95.0                     18.0       12
57.0                135.0                     9.5        5
66.0                115.0                     9.5        5
68.0                124.0                    19.8       10
72.0                160.0                    10.3        6

[870 rows x 10 columns]